[2022-06-17T11:01:05] WARNING [django.request.log_response:224] Not Found: /favicon.ico/
[2022-06-17T11:01:52] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\models.py changed, reloading.
[2022-06-17T11:03:32] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\admin.py changed, reloading.
[2022-06-17T11:03:49] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\admin.py changed, reloading.
[2022-06-17T11:20:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IHDR' 16 13
[2022-06-17T11:20:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'pHYs' 41 9
[2022-06-17T11:20:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'sRGB' 62 1
[2022-06-17T11:20:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'gAMA' 75 4
[2022-06-17T11:20:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IDAT' 91 1635740
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing BlpImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing BmpImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing BufrStubImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing CurImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing DcxImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing DdsImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing EpsImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing FitsImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing FitsStubImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing FliImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing FpxImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:404] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing FtexImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing GbrImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing GifImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing GribStubImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing Hdf5StubImagePlugin
[2022-06-17T11:20:45] DEBUG [PIL.Image.init:401] Importing IcnsImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing IcoImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing ImImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing ImtImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing IptcImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing JpegImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing Jpeg2KImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing McIdasImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing MicImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:404] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing MpegImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing MpoImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing MspImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing PalmImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing PcdImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing PcxImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing PdfImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing PixarImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing PngImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing PpmImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing PsdImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing SgiImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing SpiderImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing SunImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing TgaImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing TiffImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing WebPImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing WmfImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing XbmImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing XpmImagePlugin
[2022-06-17T11:20:46] DEBUG [PIL.Image.init:401] Importing XVThumbImagePlugin
[2022-06-17T11:26:15] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\models.py changed, reloading.
[2022-06-17T11:27:44] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\models.py changed, reloading.
[2022-06-17T11:27:51] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\models.py changed, reloading.
[2022-06-17T11:31:16] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:31:20] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:31:38] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:31:41] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:31:48] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:31:54] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:33:28] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IHDR' 16 13
[2022-06-17T11:33:28] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'pHYs' 41 9
[2022-06-17T11:33:28] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'sRGB' 62 1
[2022-06-17T11:33:28] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'gAMA' 75 4
[2022-06-17T11:33:28] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IDAT' 91 1626534
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing BlpImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing BmpImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing BufrStubImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing CurImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing DcxImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing DdsImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing EpsImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing FitsImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing FitsStubImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing FliImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing FpxImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:404] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing FtexImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing GbrImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing GifImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing GribStubImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing Hdf5StubImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing IcnsImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing IcoImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing ImImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing ImtImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing IptcImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing JpegImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing Jpeg2KImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing McIdasImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing MicImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:404] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing MpegImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing MpoImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing MspImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing PalmImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing PcdImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing PcxImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing PdfImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing PixarImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing PngImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing PpmImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing PsdImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing SgiImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing SpiderImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing SunImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing TgaImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing TiffImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing WebPImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing WmfImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing XbmImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing XpmImagePlugin
[2022-06-17T11:33:28] DEBUG [PIL.Image.init:401] Importing XVThumbImagePlugin
[2022-06-17T11:34:01] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:34:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IHDR' 16 13
[2022-06-17T11:34:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'pHYs' 41 9
[2022-06-17T11:34:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'sRGB' 62 1
[2022-06-17T11:34:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'gAMA' 75 4
[2022-06-17T11:34:45] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IDAT' 91 1635740
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing BlpImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing BmpImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing BufrStubImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing CurImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing DcxImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing DdsImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing EpsImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing FitsImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing FitsStubImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing FliImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing FpxImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:404] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing FtexImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing GbrImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing GifImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing GribStubImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing Hdf5StubImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing IcnsImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing IcoImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing ImImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing ImtImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing IptcImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing JpegImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing Jpeg2KImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing McIdasImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing MicImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:404] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing MpegImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing MpoImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing MspImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing PalmImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing PcdImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing PcxImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing PdfImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing PixarImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing PngImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing PpmImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing PsdImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing SgiImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing SpiderImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing SunImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing TgaImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing TiffImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing WebPImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing WmfImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing XbmImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing XpmImagePlugin
[2022-06-17T11:34:45] DEBUG [PIL.Image.init:401] Importing XVThumbImagePlugin
[2022-06-17T11:38:23] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\models.py changed, reloading.
[2022-06-17T11:38:32] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\models.py changed, reloading.
[2022-06-17T11:39:53] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\models.py changed, reloading.
[2022-06-17T11:42:49] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:42:59] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:43:17] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:43:26] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:43:30] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:43:41] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:43:44] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:44:05] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:44:09] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:44:19] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:44:25] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:44:33] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:44:45] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Documents\billapp\apps\views.py changed, reloading.
[2022-06-17T11:45:44] WARNING [django.request.log_response:224] Not Found: /apps/
[2022-06-17T11:46:03] INFO [root.showapps:41] bcs_seen teh whole applist
[2022-06-17T11:46:58] ERROR [django.request.log_response:224] Internal Server Error: /admin/apps/applists/edrf/change/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'edrf' for key 'apps_applists.slug'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 1660, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 1099, in save_model
    obj.save()
  File "C:\Users\saketh\Documents\billapp\apps\models.py", line 32, in save
    super(applists, self).save()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'edrf' for key 'apps_applists.slug'")
[2022-06-17T11:47:11] ERROR [django.request.log_response:224] Internal Server Error: /admin/apps/applists/edrf/change/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'edrf' for key 'apps_applists.slug'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 1660, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\options.py", line 1099, in save_model
    obj.save()
  File "C:\Users\saketh\Documents\billapp\apps\models.py", line 32, in save
    super(applists, self).save()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'edrf' for key 'apps_applists.slug'")
[2022-06-17T11:48:35] INFO [root.showapps:41] bcs_seen teh whole applist
[2022-06-17T11:48:36] INFO [root.showapps:41] bcs_seen teh whole applist
[2022-06-17T11:48:36] INFO [root.showapps:41] bcs_seen teh whole applist
[2022-06-17T11:48:53] INFO [root.showapps:41] bcs_seen teh whole applist
[2022-06-17T11:48:53] ERROR [django.request.log_response:224] Internal Server Error: /apps/applist
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\saketh\Documents\billapp\apps\views.py", line 42, in showapps
    return render(request,'showapps.html',{'showapp':appli,'leni':leni})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\files.py", line 63, in url
    self._require_file()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\files.py", line 40, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'appimg' attribute has no file associated with it.
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing BlpImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing BmpImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing BufrStubImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing CurImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing DcxImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing DdsImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing EpsImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing FitsImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing FitsStubImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing FliImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing FpxImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:404] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing FtexImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing GbrImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing GifImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing GribStubImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing Hdf5StubImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing IcnsImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing IcoImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing ImImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing ImtImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing IptcImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing JpegImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing Jpeg2KImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing McIdasImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing MicImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:404] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing MpegImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing MpoImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing MspImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing PalmImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing PcdImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing PcxImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing PdfImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing PixarImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing PngImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing PpmImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing PsdImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing SgiImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing SpiderImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing SunImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing TgaImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing TiffImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing WebPImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing WmfImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing XbmImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing XpmImagePlugin
[2022-06-17T11:49:02] DEBUG [PIL.Image.init:401] Importing XVThumbImagePlugin
[2022-06-17T11:49:06] INFO [root.showapps:41] bcs_seen teh whole applist
[2022-06-17T11:49:43] INFO [root.showapps:41] bcs_seen teh whole applist
[2022-06-17T11:50:08] INFO [root.deleteapp:51] bcs_deleted an app
[2022-06-17T11:50:08] INFO [root.showapps:41] bcs_seen teh whole applist
[2022-06-17T14:28:00] INFO [root.customerlis:115] bcs_seen the customer list
[2022-06-17T18:20:34] WARNING [django.request.log_response:224] Not Found: /favicon.ico/
